import type { LogEntry } from '../domain/types'

/**
 * A single realistic example day (2026-08-31) so the app demonstrates real
 * product value on first launch instead of an empty screen. Every entry is
 * tagged `isDemo: true` and `source: 'demo'` so it can be identified and
 * removed independently of anything the user enters — see
 * Settings → "Reset demo data". Timestamps are illustrative (the user never
 * confirmed these exact times), which is why source is "demo" rather than
 * "manual".
 *
 * Nutrition figures are reasonable midpoint estimates for the described
 * foods, not measured values — every food/drink entry is
 * measurementStatus: 'approximate' accordingly.
 */

const DEMO_DATE = '2026-08-31'
const now = new Date().toISOString()

function iso(time: string, date = DEMO_DATE): string {
  return `${date}T${time}:00+02:00`
}

export const DEMO_LOCAL_DATE = DEMO_DATE

export const demoEntries: LogEntry[] = [
  {
    id: 'demo-sleep',
    category: 'sleep',
    timestamp: iso('07:15'),
    localDate: DEMO_DATE,
    title: 'Sleep',
    detail: {
      bedTime: iso('23:30', '2026-08-30'),
      wakeTime: iso('07:15'),
      reportedDurationMin: 460,
      reportedDurationText: 'about 7-8 hours',
      quality: 4,
    },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-weight',
    category: 'weight',
    timestamp: iso('07:20'),
    localDate: DEMO_DATE,
    title: 'Body weight',
    detail: { weightKg: 95 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-croissants',
    category: 'food',
    subtype: 'meal',
    timestamp: iso('08:00'),
    localDate: DEMO_DATE,
    title: '2 croissants',
    detail: { quantity: 2, unit: 'piece', calories: 500, proteinG: 9, carbsG: 55, fatG: 27, fiberG: 2, sugarG: 8 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-cola-1',
    category: 'drink',
    subtype: 'soda',
    timestamp: iso('10:00'),
    localDate: DEMO_DATE,
    title: 'Coca-Cola 330 ml',
    detail: { volumeMl: 330, calories: 140, sugarG: 35, caffeineMg: 34 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'high',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-earl-grey',
    category: 'drink',
    subtype: 'tea',
    timestamp: iso('09:15'),
    localDate: DEMO_DATE,
    title: 'Earl Grey black tea',
    notes: 'Small cup',
    detail: { volumeMl: 200, calories: 5, caffeineMg: 30 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-spritzgeback',
    category: 'food',
    subtype: 'snack',
    timestamp: iso('11:00'),
    localDate: DEMO_DATE,
    title: 'Coconut Spritzgebäck cookies',
    detail: { quantity: 300, unit: 'g', calories: 1500, proteinG: 15, carbsG: 165, fatG: 82, fiberG: 5, sugarG: 85 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'low',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-pizza',
    category: 'food',
    subtype: 'meal',
    timestamp: iso('13:00'),
    localDate: DEMO_DATE,
    title: 'Half a small pizza',
    detail: { quantity: 0.5, unit: 'pizza', calories: 380, proteinG: 14, carbsG: 42, fatG: 16, fiberG: 2, sugarG: 4 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'low',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-cola-2',
    category: 'drink',
    subtype: 'soda',
    timestamp: iso('14:00'),
    localDate: DEMO_DATE,
    title: 'Coca-Cola 330 ml',
    detail: { volumeMl: 330, calories: 140, sugarG: 35, caffeineMg: 34 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'high',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-steps',
    category: 'steps',
    timestamp: iso('16:30'),
    localDate: DEMO_DATE,
    title: 'Walk',
    detail: { steps: 3500 },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-dorado',
    category: 'food',
    subtype: 'meal',
    timestamp: iso('15:30'),
    localDate: DEMO_DATE,
    title: 'Half dorado fish',
    detail: { quantity: 0.5, unit: 'fish', calories: 240, proteinG: 31, fatG: 12 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-cigarette',
    category: 'nicotine',
    subtype: 'cigarette',
    timestamp: iso('18:00'),
    localDate: DEMO_DATE,
    title: 'Cigarette',
    detail: { count: 1 },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-meat',
    category: 'food',
    subtype: 'meal',
    timestamp: iso('19:00'),
    localDate: DEMO_DATE,
    title: '150 g beef',
    detail: { quantity: 150, unit: 'g', calories: 320, proteinG: 34, fatG: 20 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-cola-3',
    category: 'drink',
    subtype: 'soda',
    timestamp: iso('19:30'),
    localDate: DEMO_DATE,
    title: 'Coca-Cola 330 ml',
    detail: { volumeMl: 330, calories: 140, sugarG: 35, caffeineMg: 34 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'high',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-pasta-eggs',
    category: 'food',
    subtype: 'meal',
    timestamp: iso('20:30'),
    localDate: DEMO_DATE,
    title: 'Tomato pasta + 2 eggs',
    detail: { quantity: 150, unit: 'g pasta + 2 eggs', calories: 410, proteinG: 22, carbsG: 48, fatG: 14, fiberG: 3, sugarG: 6 },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'medium',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-running',
    category: 'running',
    timestamp: iso('22:00'),
    localDate: DEMO_DATE,
    title: 'Evening run',
    detail: { distanceKm: 4, durationMin: 28, estimatedKcal: 320 },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-yogurt',
    category: 'food',
    subtype: 'snack',
    timestamp: iso('21:15'),
    localDate: DEMO_DATE,
    title: '200 g yogurt (10% fat) with date sugar & cinnamon',
    detail: {
      quantity: 200,
      unit: 'g',
      calories: 280,
      proteinG: 8,
      carbsG: 20,
      fatG: 18,
      fiberG: 1,
      sugarG: 20,
      micronutrientNote: '10-20 g date sugar and cinnamon added',
    },
    source: 'demo',
    measurementStatus: 'approximate',
    confidence: 'low',
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-energy',
    category: 'subjective',
    subtype: 'energy',
    timestamp: iso('21:00'),
    localDate: DEMO_DATE,
    detail: { rating: 3 },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-mood',
    category: 'subjective',
    subtype: 'mood',
    timestamp: iso('22:40'),
    localDate: DEMO_DATE,
    detail: { rating: 4 },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-note',
    category: 'note',
    timestamp: iso('22:45'),
    localDate: DEMO_DATE,
    detail: { text: 'Felt good after the run. Water intake was low today — should keep a bottle at the desk tomorrow.' },
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  },
]
